# Generated by Django 5.2 on 2026-02-01 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_services', '0005_product_inventory_cost_price_and_more'),
        ('orders_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders_application.cart')),
                ('product_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_services.product_inventory')),
            ],
            options={
                'unique_together': {('cart', 'product_inventory')},
            },
        ),
    ]
