# Generated by Django 5.2 on 2025-04-05 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
                ('category_description', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='colors_available',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color_details', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='size_details',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(default='', max_length=10)),
                ('size_available_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_sku', models.CharField(max_length=10, unique=True)),
                ('product_description', models.TextField(default='', max_length=1200)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_inventory', to='ecommerce_services.categories')),
                ('sizes_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes_related_info', to='ecommerce_services.size_details')),
            ],
        ),
    ]
