# Generated by Django 5.2 on 2025-04-05 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size_details',
            name='color_availability',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='color_info', to='ecommerce_services.colors_available'),
        ),
    ]
