# Generated by Django 5.2 on 2025-04-06 04:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_services', '0002_size_details_color_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_image_relation', to='ecommerce_services.product')),
            ],
        ),
    ]
