# Generated by Django 5.2 on 2026-01-21 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_services', '0003_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes_info',
        ),
        migrations.RemoveField(
            model_name='size_details',
            name='color_availability',
        ),
        migrations.RemoveField(
            model_name='size_details',
            name='size_available_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_services.categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='product_inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_quantity', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_services.colors_available')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ecommerce_services.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_services.size_details')),
            ],
            options={
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
