# Generated by Django 5.2 on 2026-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_services', '0005_product_inventory_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
